return {
PlaceObj('ModItemBuildingTemplate', {
	'Group', "Infrastructure",
	'Id', "Indoor_Drone_Hub",
	'template_class', "IndoorDroneHub",
	'pin_rollover', T(479186423602, --[[ModItemBuildingTemplate Indoor_Drone_Hub pin_rollover]] "<description><newline><newline><DronesStatusText><newline><left>Drones<right>"),
	'pin_rollover_hint', T(967239986898, --[[ModItemBuildingTemplate Indoor_Drone_Hub pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"),
	'pin_rollover_hint_xbox', T(154657083247, --[[ModItemBuildingTemplate Indoor_Drone_Hub pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"),
	'pin_summary1', T(377608732712, --[[ModItemBuildingTemplate Indoor_Drone_Hub pin_summary1]] "<DronesCount><image UI/Icons/res_drone.tga 800>"),
	'pin_on_start', true,
	'construction_cost_Metals', 4000,
	'construction_cost_Electronics', 8000,
	'build_points', 1000,
	'require_prefab', true,
	'dome_required', true,
	'maintenance_resource_type', "Electronics",
	'display_name', T(504059812895, --[[ModItemBuildingTemplate Indoor_Drone_Hub display_name]] "Indoor Drone Hub"),
	'display_name_pl', T(772614592685, --[[ModItemBuildingTemplate Indoor_Drone_Hub display_name_pl]] "Indoor Drone Hubs"),
	'description', T(462870359121, --[[ModItemBuildingTemplate Indoor_Drone_Hub description]] "Controls Drones and allocates them to different tasks."),
	'build_category', "Infrastructure",
	'display_icon', "UI/Icons/Buildings/sensor_tower.tga",
	'build_pos', 4,
	'entity', "SensorTower",
	'show_range_all', true,
	'encyclopedia_id', "DroneHub",
	'encyclopedia_image', "UI/Encyclopedia/DroneHub.tga",
	'label1', "InsideBuildings",
	'palette_color1', "outside_accent_1",
	'palette_color2', "outside_base",
	'palette_color3', "outside_metal",
	'demolish_sinking', range(10, 20),
	'demolish_debris', 85,
}),
PlaceObj('ModItemCode', {
	'name', "IndoorDroneHub",
	'FileName', "Code/IndoorDroneHub.lua",
}),
}
